/** Major Indonesian cities (kota/kabupaten) for property listings. */
export const INDONESIA_CITIES = [
  "Ambon",
  "Balikpapan",
  "Bandung",
  "Banjar",
  "Banjarmasin",
  "Batam",
  "Bekasi",
  "Bengkulu",
  "Bogor",
  "Bontang",
  "Cilegon",
  "Cimahi",
  "Cirebon",
  "Denpasar",
  "Depok",
  "Dumai",
  "Gorontalo",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Jambi",
  "Jayapura",
  "Kediri",
  "Kendari",
  "Kupang",
  "Makassar",
  "Malang",
  "Manado",
  "Mataram",
  "Medan",
  "Mojokerto",
  "Padang",
  "Palangka Raya",
  "Palembang",
  "Palu",
  "Pangkal Pinang",
  "Pekanbaru",
  "Pontianak",
  "Probolinggo",
  "Samarinda",
  "Semarang",
  "Serang",
  "Solo (Surakarta)",
  "Sorong",
  "Sukabumi",
  "Surabaya",
  "Tangerang",
  "Tangerang Selatan",
  "Tasikmalaya",
  "Tegal",
  "Ternate",
  "Yogyakarta",
].sort((a, b) => a.localeCompare(b, "id"));
